api_version = "2026-04"

[[extensions]]
name = "Product tier discounts"
handle = "product-discount"
type = "function"
uid = "d0f68f29-1841-f67e-43fd-d817ad592eda03aa57c0"
description = "Applies per-product volume discounts configured in the Product Discounts admin."

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/product-discount.wasm"
  watch = [ "src/**/*.rs" ]
